name: nil
favicon: null
layout_spectrum: 0.8910802325699478
typography_spectrum: 0.22964314720593393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9898026129230857
  lightness: 0.4323654950130731
  saturation: 0.8724843475501984
  rhythmicContrast: 0.10025072447024286
purpose: []
